apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monitoring-ingress
  namespace: {{ monitoring_namespace }}
  # annotations:
  #   nginx.ingress.kubernetes.io/rewrite-target: /
  #   nginx.ingress.kubernetes.io/proxy-body-size: 64m
  #   nginx.ingress.kubernetes.io/ssl-redirect: "true"
  #   nginx.ingress.kubernetes.io/use-regex: "false"
spec:
  ingressClassName: nginx
  # tls:
  # - hosts:
  #   - prometheus.utibe.rocks
  #   - grafana.utibe.rocks
  #   secretName: monitoring-tls-secret # Create a Kubernetes secret with TLS certificates
  rules:
  - host: prometheus.utibe.rocks
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prometheus-kube-prometheus-prometheus
            port:
              number: 9090
  - host: grafana.utibe.rocks
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prometheus-grafana
            port:
              number: 3000
