
- name: Add Prometheus Community Helm repository
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: https://prometheus-community.github.io/helm-charts

- name: Create monitoring namespace
  kubernetes.core.k8s:
    name: "{{ monitoring_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Install Kube-Prometheus Stack
  delay: 1
  retries: 3
  kubernetes.core.helm:
    name: "{{ prometheus_release_name }}"
    chart_ref: prometheus-community/kube-prometheus-stack
    release_namespace: "{{ monitoring_namespace }}"
    values:
      grafana:
        adminPassword: "{{ grafana_admin_password }}"
      prometheus:
        prometheusSpec:
          retention: 15d
          storageSpec:
            volumeClaimTemplate:
              spec:
                accessModes: ["ReadWriteOnce"]
                resources:
                  requests:
                    storage: 50Gi

- name: Create Monitoring Ingress
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'monitoring-ingress.yml') }}"
    wait: yes